name: biomercados
description: Inspirados en servir.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+1
  path_provider: ^1.6.8
  path: ^1.6.4
  intl: ^0.16.1
  cached_network_image: ^2.1.0+1
  smooth_star_rating: ^1.0.4+2
  http: ^0.12.0+4
  provider: ^4.0.5
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.7
  photo_view: ^0.9.2
  flutter_launcher_icons: ^0.7.5
  flutter_webview_plugin: ^0.3.11
  cupertino_icons: ^0.1.3
  flutter_typeahead: ^1.8.0
  flutter_phoenix: ^0.1.0
  flutter_cupertino_date_picker: ^1.0.23+1
  permission_handler: ^5.0.0+hotfix.4
  flutter_keyboard_visibility: ^0.7.0
  carousel_pro: ^1.0.0
  image_picker: ^0.6.6+4
  async: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dependency_overrides:
  intl: ^0.16.0

cupertino_icons: ^0.1.2
flutter_icons:
  #image_path: "assets/images/icon-128x128.png"
  #image_path: "assets/images/icon-1024x1024.png"
  image_path: "assets/images/icono_bio.jpg"
  
  #image_path_android: "assets/images/icon-710x599-android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"
  android: false # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/images/

  fonts:
    - family: Bree
      fonts:
        - asset: assets/fonts/bree/Bree-Regular.woff
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
        - asset: assets/fonts/dubai/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/dubai/Dubai-Bold.ttf
          weight: 700
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 900























