name: biomercados
description: Inspirados en servir

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  carousel_slider: ^1.3.1
  transparent_image: ^1.0.0
  cached_network_image: 2.0.0-rc
  smooth_star_rating: ^1.0.3
  http: ^0.12.0+2
  provider: ^4.0.5
  flutter_secure_storage: ^3.3.1+1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+3
  photo_view: ^0.9.2
  flutter_typeahead: ^1.8.0
  flutter_launcher_icons: ^0.7.4
  flutter_webview_plugin: ^0.3.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_launcher_icons:
    #path: ../

flutter_icons:
  #image_path: "assets/images/icon-128x128.png"
  #image_path: "assets/images/icon-1024x1024.png"
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-710x599-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/images/

  fonts:
    - family: Bree
      fonts:
        - asset: assets/fonts/bree/Bree-Regular.woff
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
        - asset: assets/fonts/dubai/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/dubai/Dubai-Bold.ttf
          weight: 700
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 900

    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
