name: Pide
description: pide.com.ve
version: 1.1.0+7

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #camera: ^0.8.1+1
  path_provider: ^2.0.2
  path: ^1.6.4
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  smooth_star_rating: ^1.1.1
  http: ^0.13.0
  provider: ^4.3.2
  fluttertoast: ^4.0.1
  shared_preferences: ^2.0.6
  photo_view: ^0.9.2
  flutter_launcher_icons: ^0.9.0
  flutter_webview_plugin:
    git: https://github.com/nuc134r/flutter_webview_plugin.git
  flutter_typeahead: ^3.1.3
  flutter_phoenix: ^0.1.0
  archive: ^3.1.2
  flutter_datetime_picker:
    git: https://github.com/espresso3389/flutter_datetime_picker
  flutter_keyboard_visibility: ^5.0.0
  carousel_pro: ^1.0.0
  image_picker: ^0.7.5+3
  async: ^2.6.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_countdown_timer: ^4.1.0
  responsive_framework: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



flutter_icons:
  #image_path: "assets/images/icon-128x128.png"
  #image_path: "assets/images/icon-1024x1024.png"
  image_path: "assets/images/icono_bio.jpg"
  
  #image_path_android: "assets/images/icon-710x599-android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"
  android: false # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: false
  fonts:
  - family: Pide
    fonts:
      - asset: assets/fonts/Pide.ttf
  assets:
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/images/
